version: '3.7'
services:
  wordpress:
    depends_on:
      - mysql
      - mailhog
    environment:
      SMTP_HOST: ${SMTP_HOST-mailhog}
      SMTP_PORT: ${SMTP_PORT-1025}
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - '${MAILHOG_PORT:-8025}:8025'
      - '${SMTP_PORT:-1025}:1025'
